#!/bin/bash
# =============================================================================
# Cloudflare IP Range Update Script
# =============================================================================
# This script fetches the latest Cloudflare IP ranges and updates the Nginx
# configuration for real IP extraction. Run this regularly (weekly recommended)
# to ensure new Cloudflare edge servers are recognized.
#
# Usage: ./scripts/update-cloudflare-ips.sh
# =============================================================================

set -e

CF_IPV4_URL="https://www.cloudflare.com/ips-v4"
CF_IPV6_URL="https://www.cloudflare.com/ips-v6"
OUTPUT_FILE="deploy/nginx/conf.d/cloudflare_real_ip.conf"
BACKUP_FILE="${OUTPUT_FILE}.bak"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Cloudflare IP Range Update ===${NC}"

# Backup existing file
if [ -f "$OUTPUT_FILE" ]; then
    cp "$OUTPUT_FILE" "$BACKUP_FILE"
    echo -e "${YELLOW}Backed up existing config to ${BACKUP_FILE}${NC}"
fi

# Create new configuration
cat > "$OUTPUT_FILE" << 'HEADER'
# =============================================================================
# Cloudflare Real IP Configuration
# =============================================================================
# This file is AUTO-GENERATED by scripts/update-cloudflare-ips.sh
# Do not edit manually - changes will be overwritten
#
# Purpose: Configure Nginx to extract the real client IP from Cloudflare's
# CF-Connecting-IP header. This is essential for:
# - Accurate rate limiting per client
# - Fail2ban blocking actual attackers (not Cloudflare servers)
# - Logging real client IPs for forensics
#
# Source: https://www.cloudflare.com/ips/
# =============================================================================

HEADER

echo "# Auto-generated on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Fetch and add IPv4 ranges
echo "# IPv4 Ranges" >> "$OUTPUT_FILE"
IPV4_COUNT=0
for ip in $(curl -s --fail "$CF_IPV4_URL"); do
    echo "set_real_ip_from $ip;" >> "$OUTPUT_FILE"
    ((IPV4_COUNT++))
done

if [ $IPV4_COUNT -eq 0 ]; then
    echo -e "${RED}ERROR: Failed to fetch IPv4 ranges${NC}"
    if [ -f "$BACKUP_FILE" ]; then
        mv "$BACKUP_FILE" "$OUTPUT_FILE"
        echo -e "${YELLOW}Restored backup${NC}"
    fi
    exit 1
fi

echo "" >> "$OUTPUT_FILE"

# Fetch and add IPv6 ranges
echo "# IPv6 Ranges" >> "$OUTPUT_FILE"
IPV6_COUNT=0
for ip in $(curl -s --fail "$CF_IPV6_URL"); do
    echo "set_real_ip_from $ip;" >> "$OUTPUT_FILE"
    ((IPV6_COUNT++))
done

if [ $IPV6_COUNT -eq 0 ]; then
    echo -e "${RED}ERROR: Failed to fetch IPv6 ranges${NC}"
    if [ -f "$BACKUP_FILE" ]; then
        mv "$BACKUP_FILE" "$OUTPUT_FILE"
        echo -e "${YELLOW}Restored backup${NC}"
    fi
    exit 1
fi

echo "" >> "$OUTPUT_FILE"

# Add the real_ip_header directive
cat >> "$OUTPUT_FILE" << 'FOOTER'
# Use Cloudflare's CF-Connecting-IP header for real client IP
real_ip_header CF-Connecting-IP;

# Trust recursive (nested) proxies
real_ip_recursive on;
FOOTER

echo -e "${GREEN}Successfully updated Cloudflare IP ranges${NC}"
echo -e "  IPv4 ranges: ${IPV4_COUNT}"
echo -e "  IPv6 ranges: ${IPV6_COUNT}"
echo -e "  Output file: ${OUTPUT_FILE}"

# Validate nginx config if nginx is available
if command -v nginx &> /dev/null; then
    echo -e "${YELLOW}Validating Nginx configuration...${NC}"
    if nginx -t 2>/dev/null; then
        echo -e "${GREEN}Nginx configuration is valid${NC}"
    else
        echo -e "${RED}WARNING: Nginx configuration test failed${NC}"
        echo -e "${YELLOW}Review the generated file before reloading Nginx${NC}"
    fi
fi

# Clean up backup if successful
if [ -f "$BACKUP_FILE" ]; then
    rm "$BACKUP_FILE"
fi

echo -e "${GREEN}Done!${NC}"
echo -e "${YELLOW}Remember to reload Nginx: docker-compose exec nginx nginx -s reload${NC}"